### ISSUE TITLE
Set Home Page background colour according to the rating

### ISSUE THREAD

**Issue by andrewlamyw** [andrewlamyw/mindscious#4]
- URL Location: Home Page
- Description: To provide a deeper sense of interactivity, change the background colour of the home page according to the rating value selected.

### Tasks
- [ ] Change home page background colour when the happiness rating slider is changed
- [ ] Set background to reddish colour when the rating value is low
- [ ] Set background to greenish colour when the rating value is high
